import { MD3LightTheme } from "react-native-paper"

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#2563eb",
    primaryContainer: "#dbeafe",
    secondary: "#10b981",
    secondaryContainer: "#d1fae5",
    tertiary: "#f59e0b",
    tertiaryContainer: "#fef3c7",
    surface: "#ffffff",
    surfaceVariant: "#f8fafc",
    background: "#f8fafc",
    error: "#ef4444",
    errorContainer: "#fee2e2",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#1e40af",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#065f46",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#92400e",
    onSurface: "#1f2937",
    onSurfaceVariant: "#6b7280",
    onBackground: "#1f2937",
    onError: "#ffffff",
    onErrorContainer: "#dc2626",
    outline: "#d1d5db",
    outlineVariant: "#e5e7eb",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#374151",
    inverseOnSurface: "#f9fafb",
    inversePrimary: "#93c5fd",
  },
}
